# Spec Workflow MCP Server Configuration
# 虚拟产品销售平台项目配置

# 项目目录
# 使用当前项目根目录
projectDir = "d:\\tools\\密钥网站"

# 自动启动仪表板
# 开发时自动打开 dashboard 很方便
autoStartDashboard = true

# Dashboard 端口
# 使用固定端口方便访问
port = 3456

# 语言设置
# 使用简体中文（如果支持）
lang = "zh"
